import json
import re
import keyword
from pathlib import Path

INPUT_FILE = "data/ONIX_BookProduct_Codelists_Issue_71.json"
OUTPUT_FILE = "app/models/codes_v71.py"

def sanitize_name(name):
    clean = re.sub(r'[^a-zA-Z0-9]', '_', name.upper())
    clean = re.sub(r'_+', '_', clean).strip('_')
    if not clean: return "UNKNOWN"
    if clean[0].isdigit(): clean = f"CODE_{clean}"
    if keyword.iskeyword(clean.lower()): clean = f"{clean}_CODE"
    return clean

def generate_codes():
    print(f"Reading {INPUT_FILE}...")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    codelists = data["ONIXCodeTable"]["CodeList"]
    
    lines = []
    lines.append('"""')
    lines.append('ONIX Code Lists (Issue 71) - AUTO GENERATED.')
    lines.append('Generated by scripts/generate_onix_codes.py')
    lines.append('"""')
    lines.append('')
    lines.append('from enum import Enum')
    lines.append('')
    lines.append('class OnixCode(str, Enum):')
    lines.append('    """Base class for ONIX codes."""')
    lines.append('    pass')
    lines.append('')

    for cl in codelists:
        num = cl["CodeListNumber"]
        desc = cl["CodeListDescription"]
        
        # Class definition
        class_name = f"List{num}"
        lines.append(f'class {class_name}(OnixCode):')
        lines.append('    """')
        lines.append(f'    List {num}: {desc}')
        lines.append('    """')
        
        codes = cl.get("Code", [])
        if not codes:
            lines.append('    pass')
            lines.append('')
            continue
            
        seen_keys = set()
        
        for c in codes:
            val = c["CodeValue"]
            raw_desc = c["CodeDescription"]
            key = sanitize_name(raw_desc)
            
            original_key = key
            counter = 2
            while key in seen_keys:
                key = f"{original_key}_{counter}"
                counter += 1
            seen_keys.add(key)
            
            val_escaped = val.replace('"', '\"')
            lines.append(f'    {key} = "{val_escaped}"')
            
        lines.append('')
        
    print(f"Writing to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print("Done.")

if __name__ == "__main__":
    generate_codes()